
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Infraestructure.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Bitacora_Usuario_RolServicio
{

    public int IdBitacora { get; set; }

    public int IdPuesto { get; set; }

    public string Nombre_puesto { get; set; }

    public string IdUsuario { get; set; }

    public string Nombre_usuario { get; set; }

    public bool Estado { get; set; }



    public virtual Bitacora_RolServicio Bitacora_RolServicio { get; set; }

}

}
