
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Infraestructure.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(CancionMetadata))]
    public partial class Cancion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cancion()
    {

        this.RolServicio = new HashSet<RolServicio>();

    }


    public int Id { get; set; }

    public string Nombre { get; set; }

    public string Autor { get; set; }

    public string Genero { get; set; }

    public string Url_version { get; set; }

    public string Tonalidad { get; set; }

    public System.DateTime Fecha_creacion { get; set; }

    public bool Estado { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RolServicio> RolServicio { get; set; }

}

}
